Default:
  gatewayUrl: http://127.0.0.1:30202
  mongo: mongodb://localhost:27017
  name: lite-ts
  openTracing:
    config:
      reporter:
        collectorEndpoint: http://10.10.0.66:14268/api/traces
      sampler:
        type: const
        param: 1
  port: 
    http: 9999
    grpc: 10000
  redis:
    host: 127.0.0.1
    port: 6379
LoadBalance:
  grpc:
    test: localhost:10000